// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsMnG-_kIIRFtK75id8kQ004i1SFIuy40',
    appId: '1:1066071540494:web:3c7c7116e49a40076e0d5f',
    messagingSenderId: '1066071540494',
    projectId: 'asempa-choir-app',
    authDomain: 'asempa-choir-app.firebaseapp.com',
    storageBucket: 'asempa-choir-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2lrzPY0x1Mpq7ZN7aDir-AdKlbha0uHk',
    appId: '1:1066071540494:android:0efc449e069cfdcb6e0d5f',
    messagingSenderId: '1066071540494',
    projectId: 'asempa-choir-app',
    storageBucket: 'asempa-choir-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRjfi3vt54guZlvCQSrqlnxoQVm3ZMJis',
    appId: '1:1066071540494:ios:4fd1dd9149b1037a6e0d5f',
    messagingSenderId: '1066071540494',
    projectId: 'asempa-choir-app',
    storageBucket: 'asempa-choir-app.firebasestorage.app',
    iosBundleId: 'com.example.asempaChoir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuIB_ksqKkiazAfYLimZh8y4vM51074O4',
    appId: '1:1066071540494:web:00e3d3829150557e6e0d5f',
    messagingSenderId: '1066071540494',
    projectId: 'asempa-choir-app',
    authDomain: 'asempa-choir-app.firebaseapp.com',
    storageBucket: 'asempa-choir-app.firebasestorage.app',
  );
}
